resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:36285266c563f9421f8b536b99aa69408bf4b828ef5d25479d52089e36d07c31
  name: controller
  newName: quay.io/eranco74/cluster-api-provider-agent
